---
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pycqa/pylint
    rev: v4.0.4
    hooks:
      - id: pylint
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.9.15"
    hooks:
      - id: uv-lock

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]

  - repo: local
    hooks:
      - id: oslo-config-generator
        name: Generate oslo sample config file
        language: system
        entry: /bin/bash
        args:
          - -c
          - uv run oslo-config-generator --config-file etc/dnswatch-config-generator.conf
        files: ^etc/dnswatch-config-generator\.conf$
