---
name: build-container
on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  LOCAL_IMAGE_NAME: ${{ gitea.repository }}
  DOCKERHUB_IMAGE_NAME: ednxzu/dnswatch

jobs:
  build:
    name: Run build tests
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.generate-env.outputs.environment_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate environment
        id: generate-env
        run: |
          branch_name=${{ gitea.ref }}
          echo "environment_name=$(echo $branch_name | tr '/' '-')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get build data
        id: get-build-date
        run: |
          build_date=$(date +"%Y%m%d%H%M%z")
          echo "build_date=$build_date" >> "$GITHUB_OUTPUT"

      - name: Get secrets from vault
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: "https://vault.ednz.fr"
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          secrets: |
            kv/data/cicd/gitea container_registry_uri | GITEA_REGISTRY_ADDRESS ;
            kv/data/applications/gitea/users/actions username | GITEA_REGISTRY_USERNAME ;
            kv/data/applications/gitea/users/actions token_write | GITEA_REGISTRY_TOKEN ;
            kv/data/cicd/dockerhub username | DOCKERHUB_USERNAME ;
            kv/data/cicd/dockerhub token_write | DOCKERHUB_TOKEN ;

      - name: Login to local container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.import-secrets.outputs.GITEA_REGISTRY_ADDRESS }}
          username: ${{ steps.import-secrets.outputs.GITEA_REGISTRY_USERNAME }}
          password: ${{ steps.import-secrets.outputs.GITEA_REGISTRY_TOKEN }}

      - name: Login to dockerhub container registry
        uses: docker/login-action@v3
        with:
          username: ${{ steps.import-secrets.outputs.DOCKERHUB_USERNAME }}
          password: ${{ steps.import-secrets.outputs.DOCKERHUB_TOKEN }}

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Prepare container metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE_NAME }}
            ${{ steps.import-secrets.outputs.GITEA_REGISTRY_ADDRESS }}/${{ env.LOCAL_IMAGE_NAME }}
          labels: |
            org.opencontainers.image.authors=${{ gitea.repository_owner }}
            org.opencontainers.image.created=${{ steps.get-build-date.outputs.build_date }}
            org.opencontainers.image.url=${{ gitea.event.repository.html_url }}
            org.opencontainers.image.documentation=${{ gitea.event.repository.html_url }}
            org.opencontainers.image.source=${{ gitea.event.repository.html_url }}
            org.opencontainers.image.version=${{ steps.generate-env.outputs.environment_name }}
            org.opencontainers.image.test-build=true
          tags: |
            type=raw,value=latest,enable=${{ gitea.ref_type == 'branch' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push container
        id: build-and-push
        uses: docker/build-push-action@v6
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          context: ${{ gitea.workspace }}
          file: ${{ gitea.workspace }}/Containerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: ${{ env.BUILD_PLATFORMS }}
