---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: run-pre-commits
on:
  push:

jobs:
  run-pre-commits:
    name: Run pre-commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run pre-commits
        run: |
          poetry run pre-commit run --all-files -v
